name: 'NPM Custom Action'
description: 'Installing and Caching NPM Packages'
inputs:
  path-to-holder:
    description: 'the path to cache'
    required: true
run:
  using: "composite"
  steps:
      - name: Cache NPM Dependencies
        uses: actions/cache@v3
        with:
         # npm cache files are stored in `~/.npm` on Linux/macOS
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: npm install
        shell: bash