name: Publish Package to GitHub NPM Registry

on:
  release:
    types: [published]

jobs:
  test-publish-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup NodeJS Version - 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          
      - name: Create .npmrc File
        run: |
          echo "//npm.pkg.github.com/:_authToken=\${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          echo "@MANIBATHU:registry=https://npm.pkg.github.com" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: npm install
        
      - name: Publish to GitHub Registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
